name: test-staging

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      STAGING_VARIABLE_VALUE: ${{ github.event.inputs.KRISHNA }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Test environment variable
        run: echo "The STAGING_VARIABLE_VALUE is $STAGING_VARIABLE_VALUE"
